### PR TITLE
Add ability to customize repersonalization fields

### LINKED ISSUE #25: [Repersonalisation] Make it customisable
The fields that should be customization should be defined by the user in the form of tags or field name.

### PR DESCRIPTION
**Pull request by ashrude**
fixes #25

### CODE REVIEW

**Comment by a-parida12** [comment]
@ashrude Thank you so much for working on this issue. The contribution looks good. Is it possible for you to add a test here `tests/test_03_repersonalisation.py`?

**Comment by ashrude** [comment]
Sure. I can do that tommorow

**Comment by ashrude** [comment]
Sorry it took so long, I was busy with other stuff.

I've added tests for custom fields, I believe I did them correctly but I'm not too familiar with pytest. Let my know if I did anything wrong

**Comment by a-parida12** [comment]
@ashrude thank you so much for helping out! its lgtm!

**Pull request merged**
